[versions]
junit = "5.10.2"
assertj = "3.26.0"
mockito = "5.12.0"
jackson = "2.17.1"
apache-commons-text = "1.12.0"
maven-publish = "0.28.0"
gradle-release = "3.0.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
gradle-release = { id = "net.researchgate.release", version.ref = "gradle-release" }